# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

envFrom:
  secretRef:
    name: domovoy2-service-env


ingress:
  enabled: enable
  className: ""
  annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/cluster-issuer: letsencrypt
     nginx.ingress.kubernetes.io/backend-protocol: HTTP
     nginx.ingress.kubernetes.io/enable-cors: "true"
     nginx.ingress.kubernetes.io/cors-allow-origin: "*"
     nginx.ingress.kubernetes.io/whitelist-source-range: 78.130.149.162/32, 31.13.239.28/32, 31.13.239.29/32, 31.13.239.30/32, 20.101.213.47/32, 20.101.212.95/32
     nginx.ingress.kubernetes.io/proxy-body-size: 25m
  hosts:
    - host: domovoy2-service.thepineslab.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: domovoy2-service-tls
      hosts:
        - domovoy2-service.thepineslab.net

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

service:
  type: ClusterIP
  port: 3000 
  targetPort: 3000
